#!/usr/bin/python

from chat.chat import TestCmd, Commander
from threading import Thread


def main():
    try:
        test_cmd = TestCmd()
        c = Commander('MarkSix', cmd_cb=test_cmd)
        import time

        def run():
            while True:
                time.sleep(1)
                while test_cmd.body:
                    output = test_cmd.body.pop(0)
                    c.output(output)

                while test_cmd.error:
                    output = test_cmd.error.pop(0)
                    c.output(output, "error")

        t = Thread(target=run)
        t.daemon = True
        t.start()

        # start main loop
        c.loop()
    except KeyboardInterrupt:
        pass


if __name__ == '__main__':
    main()
