#!/usr/bin/python

import sys
import os
from consumer.worker import DataManager, BettingManager
import argparse


def main(port, draw):
    """Use as the main  start up of running the program.Just write anything here
    """
    try:
        """
        There is only one thing you can do to start the server
        you can call the class method server_thread on the class
        DataServer with argument or not.If no argument has been pass
        the server will use the current ipaddress with 8084 as the
        port number by default.
        """
        server_info = """
Running on 0.0.0.0:{} (Press CTRL+C to quit)
Draw Time Interval: {}
        """.format(port, draw)

        BettingManager.DRAW_SEC = int(draw)
        DataManager.server_thread(int(port), "")

        print(server_info)
        #raise Exception("Server stop intantly")
    except OSError as ex:
        print(ex)


# check if the command line file called is the main file
if __name__ == "__main__":

    # waiting for the keyboardInterrupt action issue by the user
    try:
        # called to start the program
        parser = argparse.ArgumentParser()
        parser.add_argument('--port', nargs='?',
                            help='Port to use for the Consumer server')
        parser.add_argument('--draw', nargs='?',
                            help='Time slot for drawing')
        args = parser.parse_args()

        main(args.port or 8089, args.draw or 30)
    except KeyboardInterrupt:
        """if the program catch any key that request an interrupt
           immediate of the program.Print this message to the user.
        """
        print("\nOperation cancel by the user")
        try:
            sys.exit(0)
        except SystemExit as ex:
            print(ex)
            os._exit(0)
