version: "3.5"

networks: 
  marksix:

services:
  consumer:
    container_name: "marksix_consumer"
    build: './'
    restart: always
    networks:
      - marksix
    volumes:
      - ./:/code/
    command: sh -c "python main.py consumer --draw 100"
    ports: 
      - 9001:8089

  web_server:
    container_name: "marksix_webserver"
    build: './'
    restart: always
    networks:
      - marksix
    ports: 
      - 9002:5000
    volumes:
      - ./:/code/
    command: sh -c "python main.py web --bhost marksix_consumer --bport 8089"