#!/bin/bash


clean()
{
  for pid_file in "consumer/.pid" "web/.pid"; do

    if [ -f $pid_file ];then
      pid=`cat $pid_file`
      kill -9 $pid
    fi

  done
}


consumer(){

  destroy_consumer

  python consumer_app 1>/dev/null &

  echo $! > consumer/.pid
}

all(){
  consumer
}

web_server()
{
  python web_app 1>/dev/null &

  echo $! > web/.pid
}

chat(){

  python chat_app

}

main(){
  case $1 in

    all)
        all

    ;;
    consumer)
      consumer
    ;;

    web_server)
      web_server
    ;;

    chat)
      chat
    ;;

    *)

    ;;

  esac
}

main



